import fs from "node:fs";
import path from "node:path";
import type { ScanResult, Vulnerability, VulnChain, Severity } from "../types/index.js";

export function renderMarkdownReport(
  result: ScanResult,
  projectPath: string
): string {
  const vulns = result.confirmedVulnerabilities;
  const chains = result.chains;
  const projectName = path.basename(result.projectPath);
  const duration = (result.duration / 1000).toFixed(1);
  const trustScore = calcTrustScore(vulns, chains);
  const date = new Date(result.timestamp).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  const counts = {
    critical: vulns.filter((v) => v.severity === "critical").length,
    high: vulns.filter((v) => v.severity === "high").length,
    medium: vulns.filter((v) => v.severity === "medium").length,
    low: vulns.filter((v) => v.severity === "low").length,
  };

  let md = `# Security Report: ${projectName}

**Date:** ${date}
**Scanned by:** sphinx-agent v1.0.0
**Duration:** ${duration}s | **Files:** ${result.filesScanned} | **Languages:** ${result.languages.join(", ") || "N/A"}

---

## Executive Summary

| Metric | Value |
|--------|-------|
| **Trust Score** | **${trustScore.toFixed(1)}/10** ${trustScore >= 7 ? "✅" : trustScore >= 4 ? "⚠️" : "❌"} |
| Total Findings | ${vulns.length} |
| Critical | ${counts.critical} |
| High | ${counts.high} |
| Medium | ${counts.medium} |
| Low | ${counts.low} |
| Attack Chains | ${chains.length} |
| False Positives Dismissed | ${result.dismissedCount} |

`;

  if (trustScore >= 7) {
    md += `> **Overall Assessment:** The project has a good security posture. Address the remaining findings to improve further.\n\n`;
  } else if (trustScore >= 4) {
    md += `> **Overall Assessment:** Several security issues require attention. Prioritize critical and high severity findings.\n\n`;
  } else {
    md += `> **Overall Assessment:** ⚠️ Critical security issues found. Immediate remediation recommended before deployment.\n\n`;
  }

  // Attack Chains
  if (chains.length > 0) {
    md += `## Attack Chains\n\n`;
    md += `The following multi-step attack paths were identified:\n\n`;

    for (const chain of chains) {
      md += `### ${severityBadge(chain.severity)} ${chain.title}\n\n`;
      md += `**Impact:** ${chain.impact}\n\n`;
      md += `| Step | File | Finding |\n|------|------|---------|\n`;
      for (let i = 0; i < chain.vulnerabilities.length; i++) {
        const v = chain.vulnerabilities[i];
        md += `| ${i + 1} | \`${v.location.file}:${v.location.line}\` | ${v.title} |\n`;
      }
      md += `\n> ${chain.narrative}\n\n`;
    }
  }

  // Findings by severity
  md += `## Findings\n\n`;

  for (const severity of ["critical", "high", "medium", "low"] as Severity[]) {
    const group = vulns.filter((v) => v.severity === severity);
    if (group.length === 0) continue;

    md += `### ${severityBadge(severity)} ${severity.charAt(0).toUpperCase() + severity.slice(1)} (${group.length})\n\n`;

    for (const v of group) {
      md += `#### ${v.id}: ${v.title}\n\n`;
      md += `- **File:** \`${v.location.file}:${v.location.line}\`\n`;
      md += `- **Category:** ${v.category}`;
      if (v.cwe) md += ` | **CWE:** ${v.cwe}`;
      if (v.aiVerified) md += ` | **AI Verified** ✓`;
      md += `\n`;
      md += `- **Description:** ${v.description}\n`;
      if (v.location.snippet) {
        md += `\n\`\`\`\n${v.location.snippet}\n\`\`\`\n`;
      }
      md += `\n`;
    }
  }

  // Recommendations
  md += `## Recommendations\n\n`;
  md += `1. **Immediate:** Fix all ${counts.critical} critical findings before next deployment\n`;
  if (counts.high > 0) md += `2. **Short-term:** Address ${counts.high} high severity findings within this sprint\n`;
  if (counts.medium > 0) md += `3. **Medium-term:** Review and fix ${counts.medium} medium severity findings\n`;
  if (chains.length > 0) md += `4. **Priority:** Break the ${chains.length} attack chain(s) by fixing the first vulnerability in each chain\n`;
  md += `\nRun \`sphinx-agent fix --apply\` to auto-generate patches for applicable findings.\n\n`;

  md += `---\n\n*Generated by [sphinx-agent](https://github.com/sphinx-agent/sphinx-agent) — The AI security agent that guards your code.*\n`;

  return md;
}

export function saveMarkdownReport(
  result: ScanResult,
  projectPath: string
): string {
  const md = renderMarkdownReport(result, projectPath);
  const dir = path.join(projectPath, ".sphinx");
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const outputPath = path.join(dir, "report.md");
  fs.writeFileSync(outputPath, md, "utf-8");
  return outputPath;
}

function severityBadge(s: Severity): string {
  switch (s) {
    case "critical": return "🔴";
    case "high": return "🟠";
    case "medium": return "🟡";
    case "low": return "🔵";
    default: return "⚪";
  }
}

function calcTrustScore(vulns: Vulnerability[], chains: VulnChain[]): number {
  let score = 10;
  for (const v of vulns) {
    switch (v.severity) { case "critical": score -= 2; break; case "high": score -= 1; break; case "medium": score -= 0.5; break; case "low": score -= 0.2; break; }
  }
  for (const c of chains) {
    switch (c.severity) { case "critical": score -= 1.5; break; case "high": score -= 1; break; default: score -= 0.5; }
  }
  return Math.max(0, Math.min(10, score));
}
