import path from "node:path";
import fs from "node:fs";
import chalk from "chalk";
import { loadHistory } from "../../store/history.js";

interface ChangelogOptions {
  path?: string;
  last: number;
  md?: boolean;
}

export async function changelogCommand(options: ChangelogOptions) {
  const projectPath = path.resolve(options.path || ".");
  const history = loadHistory(projectPath);

  if (history.scans.length < 2) {
    console.log(
      chalk.yellow(
        "\n⚠️  Need at least 2 scans for a changelog. Run mythos-agent scan multiple times.\n"
      )
    );
    return;
  }

  const scans = history.scans.slice(-options.last);
  const projectName = path.basename(projectPath);

  if (options.md) {
    const md = generateMarkdownChangelog(scans, projectName);
    const outputPath = path.join(projectPath, ".sphinx", "security-changelog.md");
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(outputPath, md);
    console.log(chalk.green(`\n✅ Changelog saved to ${outputPath}\n`));
    return;
  }

  // Terminal output
  console.log(chalk.bold(`\n📜 Security Changelog — ${projectName}\n`));
  console.log(chalk.dim("━".repeat(50)));

  for (let i = scans.length - 1; i >= 1; i--) {
    const curr = scans[i];
    const prev = scans[i - 1];
    const date = new Date(curr.timestamp).toLocaleDateString();
    const delta = curr.total - prev.total;
    const scoreDelta = curr.trustScore - prev.trustScore;

    console.log(chalk.bold(`\n  ${date}`));
    console.log(
      `    Findings: ${prev.total} → ${curr.total} (${delta <= 0 ? chalk.green(String(delta)) : chalk.red(`+${delta}`)})` +
        `    Score: ${prev.trustScore.toFixed(1)} → ${curr.trustScore.toFixed(1)} (${scoreDelta >= 0 ? chalk.green(`+${scoreDelta.toFixed(1)}`) : chalk.red(scoreDelta.toFixed(1))})`
    );

    if (delta < 0) {
      console.log(chalk.green(`    ✅ ${Math.abs(delta)} finding(s) fixed`));
    } else if (delta > 0) {
      console.log(chalk.red(`    🔺 ${delta} new finding(s) introduced`));
    }

    if (curr.critical !== prev.critical) {
      const cd = curr.critical - prev.critical;
      console.log(`    Critical: ${cd > 0 ? chalk.red(`+${cd}`) : chalk.green(String(cd))}`);
    }
  }

  console.log();
}

function generateMarkdownChangelog(
  scans: Array<{
    timestamp: string;
    total: number;
    critical: number;
    high: number;
    medium: number;
    low: number;
    trustScore: number;
  }>,
  projectName: string
): string {
  let md = `# Security Changelog — ${projectName}\n\n`;
  md += `Generated by mythos-agent\n\n---\n\n`;

  for (let i = scans.length - 1; i >= 1; i--) {
    const curr = scans[i];
    const prev = scans[i - 1];
    const date = new Date(curr.timestamp).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
    const delta = curr.total - prev.total;
    const scoreDelta = curr.trustScore - prev.trustScore;

    md += `## ${date}\n\n`;
    md += `| Metric | Before | After | Delta |\n`;
    md += `|--------|--------|-------|-------|\n`;
    md += `| Total | ${prev.total} | ${curr.total} | ${delta > 0 ? `+${delta}` : delta} |\n`;
    md += `| Critical | ${prev.critical} | ${curr.critical} | ${curr.critical - prev.critical > 0 ? `+${curr.critical - prev.critical}` : curr.critical - prev.critical} |\n`;
    md += `| High | ${prev.high} | ${curr.high} | ${curr.high - prev.high > 0 ? `+${curr.high - prev.high}` : curr.high - prev.high} |\n`;
    md += `| Trust Score | ${prev.trustScore.toFixed(1)} | ${curr.trustScore.toFixed(1)} | ${scoreDelta >= 0 ? `+${scoreDelta.toFixed(1)}` : scoreDelta.toFixed(1)} |\n\n`;

    if (delta < 0) md += `> ✅ ${Math.abs(delta)} finding(s) fixed\n\n`;
    else if (delta > 0) md += `> ⚠️ ${delta} new finding(s) introduced\n\n`;
    else md += `> No change\n\n`;
  }

  return md;
}
