import fs from "node:fs";
import path from "node:path";
import http from "node:http";
import chalk from "chalk";
import ora from "ora";
import {
  discoverLockfiles,
  parseLockfile,
  type Dependency,
} from "../../scanner/lockfile-parsers.js";
import { DepScanner } from "../../scanner/dep-scanner.js";

interface DepsOptions {
  path?: string;
  port: number;
  json?: boolean;
}

export async function depsCommand(options: DepsOptions) {
  const projectPath = path.resolve(options.path || ".");
  const lockfiles = discoverLockfiles(projectPath);

  if (lockfiles.length === 0) {
    console.log(chalk.yellow("\n⚠️  No lockfiles found.\n"));
    return;
  }

  const spinner = ora("Analyzing dependencies...").start();

  const allDeps: Dependency[] = [];
  for (const lf of lockfiles) allDeps.push(...parseLockfile(lf));

  // Deduplicate
  const seen = new Set<string>();
  const deps = allDeps.filter((d) => {
    const key = `${d.name}@${d.version}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  // Check for vulnerabilities
  let vulnDeps = new Set<string>();
  try {
    const depScanner = new DepScanner();
    const { findings } = await depScanner.scan(projectPath);
    vulnDeps = new Set(findings.map((f) => f.location.snippet?.split(" ")[0] || ""));
    spinner.succeed(`${deps.length} dependencies, ${findings.length} vulnerabilities`);
  } catch {
    spinner.succeed(`${deps.length} dependencies (OSV check skipped)`);
  }

  if (options.json) {
    console.log(
      JSON.stringify(
        deps.map((d) => ({
          ...d,
          vulnerable: vulnDeps.has(`${d.name}@${d.version}`),
        })),
        null,
        2
      )
    );
    return;
  }

  // Serve interactive HTML
  const html = buildDepsHtml(deps, vulnDeps, projectPath);
  const server = http.createServer((_req, res) => {
    res.writeHead(200, { "Content-Type": "text/html" });
    res.end(html);
  });

  server.listen(options.port, "127.0.0.1", () => {
    console.log(
      chalk.bold(`\n📦 Dependency graph: ${chalk.cyan(`http://localhost:${options.port}`)}\n`)
    );
  });
}

function buildDepsHtml(deps: Dependency[], vulnDeps: Set<string>, projectPath: string): string {
  const projectName = path.basename(projectPath);
  const byEcosystem = new Map<string, Dependency[]>();
  for (const d of deps) {
    const list = byEcosystem.get(d.ecosystem) || [];
    list.push(d);
    byEcosystem.set(d.ecosystem, list);
  }

  const ecosystemSections = [...byEcosystem.entries()]
    .map(([eco, ecoDeps]) => {
      const rows = ecoDeps
        .map((d) => {
          const isVuln = vulnDeps.has(`${d.name}@${d.version}`);
          return `<tr class="${isVuln ? "vuln" : ""}">
        <td>${isVuln ? "🔴" : "✅"}</td>
        <td><strong>${esc(d.name)}</strong></td>
        <td>${esc(d.version)}</td>
        <td>${esc(d.lockfile)}</td>
      </tr>`;
        })
        .join("");
      const vulnCount = ecoDeps.filter((d) => vulnDeps.has(`${d.name}@${d.version}`)).length;
      return `<h2>${esc(eco)} (${ecoDeps.length} packages${vulnCount > 0 ? `, <span class="red">${vulnCount} vulnerable</span>` : ""})</h2>
    <table><thead><tr><th></th><th>Package</th><th>Version</th><th>Lockfile</th></tr></thead><tbody>${rows}</tbody></table>`;
    })
    .join("");

  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Dependencies — ${esc(projectName)}</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#0a0a0f;color:#e0e0e0;padding:2rem}
h1{font-size:1.4rem;margin-bottom:1rem}h2{font-size:1.1rem;margin:1.5rem 0 0.5rem;color:#f8fafc}
table{width:100%;border-collapse:collapse;margin-bottom:1rem}th{text-align:left;padding:0.5rem;font-size:0.75rem;color:#64748b;border-bottom:1px solid #1e293b}
td{padding:0.5rem;border-bottom:1px solid #111827;font-size:0.85rem}tr:hover td{background:#111827}
tr.vuln td{background:#1a0a0a}tr.vuln td:nth-child(2){color:#ef4444}
.red{color:#ef4444}.stats{display:flex;gap:1rem;margin-bottom:1.5rem}.stat{background:#111827;border:1px solid #1e293b;border-radius:8px;padding:1rem;text-align:center;min-width:100px}
.stat .num{font-size:2rem;font-weight:800}.stat .label{font-size:0.7rem;color:#64748b;text-transform:uppercase}
footer{text-align:center;color:#374151;font-size:0.75rem;margin-top:2rem;padding-top:1rem;border-top:1px solid #1e293b}
</style></head><body>
<h1>📦 Dependencies — ${esc(projectName)}</h1>
<div class="stats">
<div class="stat"><div class="num">${deps.length}</div><div class="label">Total</div></div>
<div class="stat"><div class="num" style="color:#ef4444">${vulnDeps.size}</div><div class="label">Vulnerable</div></div>
<div class="stat"><div class="num">${byEcosystem.size}</div><div class="label">Ecosystems</div></div>
</div>
${ecosystemSections}
<footer>Generated by sphinx-agent</footer>
</body></html>`;
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
